.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_Kernel_Release_Notes

Kernel Release Notes
======================

Build Information
-------------------
Please refer to `Kernel Build Information <Release_Specific_Release_Notes.html#linux-kernel>`__ for details.

Generic Kernel Release Notes
------------------------------
Please refer to `Generic Kernel Release Notes <Release_Specific_Release_Notes.html#generic-kernel-release-notes>`__ for details.


Known Issues
--------------
Please refer to `Linux Kernel Known Issues <Release_Specific_Release_Notes.html#linux-kernel-known-issues>`__ for details.

