.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_Kernel_Release_Notes

Kernel Release Notes
======================

Build Information
-------------------

.. ifconfig:: CONFIG_sdk in ('PLSDK')

    Please refer to `Kernel Build Information <Release_Specific_PLSDK_Release_Notes.html#linux-kernel>`__ for details.

.. ifconfig:: CONFIG_sdk in ('PSDKLA')

    Please refer to Yocto build for details.

Generic Kernel Release Notes
------------------------------

.. ifconfig:: CONFIG_sdk in ('PLSDK')

    Please refer to `Generic Kernel Release Notes <Release_Specific_PLSDK_Release_Notes.html#generic-kernel-release-notes>`__ for details.

.. ifconfig:: CONFIG_sdk in ('PSDKLA')

    TODO


Known Issues
--------------

.. ifconfig:: CONFIG_sdk in ('PLSDK')

    Please refer to `Linux Kernel Known Issues <Release_Specific_PLSDK_Release_Notes.html#linux-kernel-known-issues>`__ for details.

.. ifconfig:: CONFIG_sdk in ('PSDKLA')

    TODO

