.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_RT_Kernel_Release_Notes

RT Kernel Release Notes
========================

Build Information
-------------------
Please refer to `RT Linux Kernel Build Information <Release_Specific_PLSDK_Release_Notes.html#real-time-rt-linux-kernel>`__ for details.

Generic Kernel Release Notes
------------------------------
Please refer to `Generic Kernel Release Notes <Release_Specific_PLSDK_Release_Notes.html#generic-kernel-release-notes>`__ for details.


Known Issues
--------------
Please refer to `RT Linux Kernel Known Issues <Release_Specific_PLSDK_Release_Notes.html#rt-linux-kernel-known-issues>`__ for details.

