---
# yamllint disable rule:line-length
# Each component identified by its path prefix has a list of owners
components:

  # Ownership applies recursively to any file in a directory
  source/linux/Foundational_Components/Kernel/Kernel_Drivers/Network: &linux_net_list
    - Siddharth-Vadapalli-at-TI
    - chintan013
    - danish-ti
  source/linux/Foundational_Components/Kernel/Kernel_Drivers/PCIe: *linux_net_list
  source/linux/Foundational_Components/Kernel/Kernel_Drivers/USB: *linux_net_list
  source/linux/Foundational_Components/PRU-ICSS*: *linux_net_list
  source/linux/Foundational_Components_PRU_Subsystem.rst: *linux_net_list

  source/android: &android_list
    - glaroque
    - makohoek
    - vishalmti
  source/devices/*/android: *android_list

  source/system: &mpu_list
    - texasinstruments/sitara-mpu-linux-sdk
  source/buildroot: *mpu_list
  source/linux/Foundational_Components/Hypervisor: *mpu_list
  source/linux/Foundational_Components/Tools: *mpu_list
  source/linux/Foundational_Components/Virtualization: *mpu_list
  source/debian: *mpu_list
  source/devices/*/debian: *mpu_list

  source/devices/AM335x/linux: &sitara_legacy_list
    - jeevantelukula
    - jmenti
  source/devices/AM437x/linux: *sitara_legacy_list
  source/devices/AM65X/linux: *sitara_legacy_list

  source/devices/AM64X/linux:
    - Pratham-T

  source/devices/AM62X/linux:
    - santhosh21

  source/devices/AM62AX/linux:
    - cshilwant
    - PrathamTI

  source/devices/AM62AX/edgeai:
    - cshilwant
    - Akshay-Abdar

  source/devices/AM62DX/linux:
    - paresh-bhagat12

  source/devices/AM62PX/linux:
    - jeevantelukula
    - jainswamil

  source/devices/AM62LX/linux:
    - bryanbrattlof
    - sskartheekadivi

  source/linux/Overview:
    - praneethbajjuri
    - gehariprasath
    - uditkumarti
    - ti-sebin

  source/linux/Release_Specific:
    - jeevantelukula
    - praneethbajjuri
    - uditkumarti
    - gehariprasath

  source/linux/Foundational_Components:
    - devarsht
    - praneethbajjuri
    - ti-sebin
    - uditkumarti
    - gehariprasath

  source/linux/Foundational_Components/IPC:
    - 3V3RYONE
    - h-nagalla
    - jmenti

  source/linux/Foundational_Components/U-Boot:
    - bryanbrattlof
    - jmenti
    - ArchUsr64

  source/linux/Foundational_Components/Kernel:
    - devarsht
    - praneethbajjuri
    - ti-sebin
    - r-vignesh
    - uditkumarti
    - gehariprasath

  source/linux/Foundational_Components/Power_Management:
    - vishalmti
    - kwillis01
    - ti-scaria

  source/linux/Foundational_Components/Graphics:
    - Antonios-C
    - DarrenEtheridge
    - StaticRocket
