******************
IPC
******************

Overview
==================================
.. include:: Foundational_Components/IPC/IPC_Overview.rst.inc

IPC Quick Start Guide
==================================
.. include:: Foundational_Components/IPC/Quick_Start_Guide.rst.inc

IPC for AM57xx
==================================
.. include:: Foundational_Components/IPC/IPC_for_AM57xx.rst.inc

IPC for AM65xx
==================================
.. include:: Foundational_Components/IPC/IPC_for_AM65xx.rst.inc

Multiple Ways of ARM-DSP Communication
=======================================
.. include:: Foundational_Components/IPC/Multiple_Ways_of_ARM-DSP_Communication.rst.inc
