Getting Started with PRU-ICSS
==================================
.. include:: ../common/PRU-ICSS/Getting_Started.rst.inc

Header Files
==================================
.. include:: ../common/PRU-ICSS/Header_Files.rst.inc


Linux Drivers
==================================

RemoteProc and RPMsg
-----------------------------------------
.. include:: Foundational_Components/PRU-ICSS/Linux_Drivers/RemoteProc_and_RPMsg.rst.inc

PRU-ICSS Ethernet
-----------------------------------------
.. include:: Foundational_Components/PRU-ICSS/Linux_Drivers/PRU-ICSS_Ethernet.rst.inc



