Getting Started with PRU-ICSS
==================================
.. include:: ../common/PRU-ICSS/Getting_Started.rst.inc

Header Files
==================================
.. include:: ../common/PRU-ICSS/Header_Files.rst.inc


Linux Drivers
==================================

RemoteProc and RPMsg
-----------------------------------------
.. include:: Foundational_Components/PRU-ICSS/Linux_Drivers/RemoteProc_and_RPMsg.rst.inc

PRU-ICSS Ethernet
-----------------------------------------
.. include:: Foundational_Components/PRU-ICSS/Linux_Drivers/PRU-ICSS_Ethernet.rst.inc

PRU_ICSSG Ethernet
-----------------------------------------
.. include:: Foundational_Components/PRU-ICSSG/Linux_Drivers/PRU_ICSSG_Ethernet.rst.inc

PRU-ICSS Soft UART
-----------------------------------------
.. include:: Foundational_Components/PRU-ICSS/Linux_Drivers/pru-sw-uart.rst.inc

Linux User Space
==================================

ICSS_EMAC
-----------------------------------------
.. include:: Foundational_Components/PRU-ICSS/Linux_User_Space/ICSS_EMAC.rst.inc
