******************
Tools
******************

Flash Tools
==================================

Sitara Uniflash
---------------------------------

.. include:: Foundational_Components/Tools/Flash_Tools/Sitara_Uniflash.rst.inc

AM335x Flash
---------------------------------
.. include:: Foundational_Components/Tools/Flash_Tools/AM335x_Flash.rst.inc

Pin Mux Tools
==================================
.. include:: Foundational_Components/Tools/Pin_Mux_Tools.rst.inc

Code Composer Studio
==================================

CCS Installation
---------------------------------
.. include:: Foundational_Components/Tools/Code_Composer_Studio/CCS_Installation.rst.inc

CCS Compiling
---------------------------------
.. include:: Foundational_Components/Tools/Code_Composer_Studio/CCS_Compiling.rst.inc

Remote Explorer Setup with CCS
---------------------------------
.. include:: Foundational_Components/Tools/Code_Composer_Studio/Remote_Explorer_Setup_with_CCS.rst.inc

GDB Setup with CCS
---------------------------------
.. include:: Foundational_Components/Tools/Code_Composer_Studio/GDB_Setup_with_CCS.rst.inc

Kernel Debugging with CCS
---------------------------------
.. include:: Foundational_Components/Tools/Code_Composer_Studio/Kernel_Debugging_with_CCS.rst.inc
