.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_Tools

******************
Tools
******************

There are many tools available to help with Linux development on TI
platforms. From Code Composer Studio, an Eclipse IDE that can be used
for debug and development, to scripts and production tools, you'll
find a variety of help on this page.

Development Tools
==================================

Processor SDK Linux Top-Level Makefile
-------------------------------------------------
Please refer to `Top-Level Makefile <Overview.html#processor-sdk-linux-top-level-makefile>`__ for details.


Processor SDK Linux GCC Toolchain
-------------------------------------------------
Please refer to `GCC ToolChain <Overview.html#gcc-toolchain>`__ for details.

Creating SD Cards
-------------------------------------------------
Please refer to `Linux SD Card Creation Guide <Overview.html#linux-sd-card-creation-guide>`__ for details.


Processor SDK Linux Setup Script
-------------------------------------------------
Please refer to `Run Setup Scripts <Overview.html#run-setup-scripts>`__ for details.


Flash Tools
==================================

Sitara Uniflash
---------------------------------

.. include:: Foundational_Components/Tools/Flash_Tools/Sitara_Uniflash.rst.inc

AM335x Flash
---------------------------------
.. include:: Foundational_Components/Tools/Flash_Tools/AM335x_Flash.rst.inc

Pin Mux Tools
==================================
.. include:: Foundational_Components/Tools/Pin_Mux_Tools.rst.inc

Code Composer Studio
==================================

CCS Installation
---------------------------------
.. include:: Foundational_Components/Tools/Code_Composer_Studio/CCS_Installation.rst.inc

CCS Compiling
---------------------------------
.. include:: Foundational_Components/Tools/Code_Composer_Studio/CCS_Compiling.rst.inc

Remote Explorer Setup with CCS
---------------------------------
.. include:: Foundational_Components/Tools/Code_Composer_Studio/Remote_Explorer_Setup_with_CCS.rst.inc

GDB Setup with CCS
---------------------------------
.. include:: Foundational_Components/Tools/Code_Composer_Studio/GDB_Setup_with_CCS.rst.inc

Kernel Debugging with CCS
---------------------------------
.. include:: Foundational_Components/Tools/Code_Composer_Studio/Kernel_Debugging_with_CCS.rst.inc
