.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_Migration_Guide

************************************
Processor SDK Linux Migration Guide
************************************

.. rubric:: Overview

This page covers migration information for applications built on top
of the Processor SDK for Linux.

Processor SDK 09.xx Releases
================================

Processor SDK Jacinto 09.00
-------------------------------
- This is the first release in the 2023 LTS stream 6.1 kernel, 2023.04 U-Boot and Yocto Kirkstone/4.0
- ATF 2.8+
- OPTEE 3.20
- Yocto Kirkstone/4.0
- Platforms Supported : J721E, J7200, J721S2, J784S4, AM68, AM69
- k3-image-gen and core-secdev-k3 are no longer needed for U-Boot build, new build flow can be seen :ref:`here <Build-U-Boot-label>`.

Processor SDK 08.xx Releases
================================

Processor SDK Jacinto 08.06
-------------------------------
- This is the ninth release on 2021 LTS 5.10 kernel, 2021.01 U-Boot
- ATF 2.8
- OPTEE 3.20
- Yocto Dunfell/3.1
- Platforms Supported : J721E, J7200, J721S2, J784S4, AM68A, AM69A

Processor SDK Jacinto 08.05
-------------------------------
- This is the seventh release on 2021 LTS 5.10 kernel, 2021.01 U-Boot
- ATF 2.7
- OPTEE 3.19
- Yocto Dunfell/3.1
- Platforms Supported : J721E, J7200, J721S2, J784S4

Processor SDK Jacinto 08.04
-------------------------------
- This is the fifth release on 2021 LTS 5.10 kernel, 2021.01 U-Boot
- ATF 2.6
- OPTEE 3.12
- Yocto Dunfell/3.1
- Platforms Supported : J721E, J7200, J721S2


Processor SDK 08.02
-----------------------
- This is the third release on 2021 LTS 5.10 kernel, 2021.01 U-Boot

- Third release on 5.10 kernel and 2021.01 U-boot
- ATF 2.5
- OPTEE 3.12
- Yocto Dunfell/3.1
- Platforms Supported : J721E, J721S2, J7200


Processor SDK 08.01
-----------------------
- This is the second release on 2021 LTS 5.10 kernel, 2021.01 U-Boot

- Second release on 5.10 kernel and 2021.01 U-boot
- ATF 2.5
- OPTEE 3.12
- Yocto Dunfell/3.1
- Platforms Supported : J721E, J7200


Processor SDK 08.00
-----------------------
- This is the first release in the 2021 LTS stream, with new versions of Kernel, U-boot, toolchain and Yocto branch.`

- First release on 5.10 kernel and 2021.01 U-boot
- ATF 2.5
- OPTEE 3.12
- Yocto Dunfell/3.1
- Platforms Supported : J721E, J7200
