.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_Migration_Guide

************************************
Processor SDK Linux Migration Guide
************************************

.. rubric:: Overview

This page covers migration information for applications built on top
of the Processor SDK for Linux.

Processor SDK 09.xx Releases
================================

Processor SDK Jacinto 09.00
-------------------------------
- This is the first release in the 2023 LTS stream 6.1 kernel, 2023.04 U-Boot and Yocto Kirkstone/4.0
- ATF 2.8+
- OPTEE 3.20
- Yocto Kirkstone/4.0
- Platforms Supported : J721E, J7200, J721S2, J784S4, AM68, AM69
- k3-image-gen and core-secdev-k3 are no longer needed for U-Boot build, new build flow can be seen :ref:`here <Build-U-Boot-label>`.
