Thank you for choosing to evaluate one of our TI Processors `ARM
microprocessors <http://www.ti.com/lsds/ti/dsp/arm.page>`__. Please
bookmark this page and refer back to it as needed. It is designed to
quickly provide the information you need most while evaluating a TI
microprocessor, specifically running one of the Software Architectures
available, embedded Android. We are always striving to improve this
product.  Please let us know if you have `ideas or
suggestions <index.html#feedback>`__.

.. rubric:: Version
   :name: version

This information covers Processor SDK Android 4.0.0 and above.

+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| **Processor SDK Android**                                                                                                                              |
+========================================================================+===============================================================================+
| `Getting Started Guide`_  <-- **Start Here**                           | `How To Guides`_                                                              |
+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| `Supported Platforms and Versions`_                                    | `Android Software Stack`_                                                     |
+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| `Directory Structure Overview`_                                        | `Building the SDK`_                                                           |
+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| `Release Notes`_                                                       | `Frequently Asked Questions`_                                                 |
+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| `GPLv3 Disclaimer`_                                                    | `Migration Guide`_                                                            |
+------------------------------------------------------------------------+-------------------------------------------------------------------------------+
| `Technical Support`_                                                   | `Training <https://training.ti.com/processor-sdk-training-series>`__          |
+------------------------------------------------------------------------+-------------------------------------------------------------------------------+

.. _Getting Started Guide: Overview_Getting_Started_Guide.html
.. _Supported Platforms and Versions: Release_Specific_Supported_Platforms_and_Versions.html
.. _Release Notes: Release_Specific_Release_Notes.html
.. _Android Software Stack: Overview_Software_Stack.html
.. _Migration Guide: Release_Specific_Migration_Guide.html
.. _Frequently Asked Questions: Processor_SDK_Android_How_To_Guides.html#frequently-asked-questions
.. _GPLv3 Disclaimer: Overview_GPLv3_Disclaimer.html
.. _How To Guides: Processor_SDK_Android_How_To_Guides.html
.. _Directory Structure Overview: Overview_Directory_Structure.html
.. _Building the SDK: Overview_Building_the_SDK.html
.. _Technical Support: Overview_Technical_Support.html


.. rubric:: Feedback
   :name: feedback

If you have feedback, suggestions, or ideas on how to improve the SDK,
it is very appreciated. Please post your ideas to the `E2E Processor
Support <https://e2e.ti.com/support/processors/>`__ Forum.

