.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_Software_Stack

************************************
Software Stack
************************************

The following software stack illustrates at a high level the various
components provided with the Processor SDK for Linux.

.. note::
   **Availability of certain applications are platform dependent
   and clarified in the associated User Guides.**

.. ifconfig:: CONFIG_part_family in ('General_family', 'AM335X_family', 'AM437X_family')

   .. Image:: ../images/Processor_SDK_linux_stack_v3.png

.. ifconfig:: CONFIG_part_family in ('J7_family')

   .. Image:: ../images/Processor_SDK_Auto_linux_stack.png
