#!/bin/bash

# SPDX-License-Identifier: MIT
# Copyright (C) 2024 Texas Instruments Incorporated - https://www.ti.com

get_build_uid() {
	stat -c '%u' /build
}

get_build_gid() {
	stat -c '%g' /build
}

if NEW_GID=$(get_build_gid) && NEW_UID=$(get_build_uid); then
	# bypass everything if podman is remapping the id to root
	if [ "${NEW_UID}" == "0" ]; then
		if [ "$(id -u)" == "0" ]; then
			exec dumb-init -- "$@"
		else
			echo "Unable to resolve ns mapping!"
		fi
	fi

	# change the uid and gid of abc otherwise
	[ "$NEW_GID" != "$(id -g abc)" ] && groupmod -g "${NEW_GID}" abc
	[ "$NEW_UID" != "$(id -u abc)" ] && usermod -u "${NEW_UID}" abc
else
	echo "Not able to detect UID/GID for remapping!"
fi

if [ "$(id -u)" == "$(id -u abc)" ]; then
	exec dumb-init -- "$@"
else
	exec dumb-init -- su-exec abc:abc "$@"
fi
