Minimal Platform Development
============================

When customers purchase or develop custom boards using the TI AM62x 
family of SoCs, the heavy integration of the existing code base results 
in upbringing time that ranges from a few days to several weeks. If a 
developer would like to create a custom board using TI's AM62x SoC, they 
must edit both the device tree and configuration files used for the TI 
boards to fit their new independent layout with differing peripherals. 
This application note introduces a minimal configuration to streamline 
this process and reduce the time of this initial upbringing process to 
around one day, and as shown in the case study, as little as two hours.
Use the application note below to begin minimal platform development for
custom boards using the TI AM62x.

`Minimal Platform Development on AM62x Devices <https://www.ti.com/lit/pdf/spradd1>`__
