*******************************
Migration Guide
*******************************
.. rubric:: Overview
   :name: overview

This page covers migration information for applications built on top
of the Processor SDK for Android.

.. rubric:: Processor SDK Android 05.03.00
   :name: processor-sdk-android-05.03.00

-  This release includes the first version of the Processor SDK Android for AM65x with Oreo
-  This release includes maintenance update of the Processor SDK Android for AM57xx
   with Oreo.
-  More details about Oreo can be obtained from
   `here <https://developer.android.com/about/versions/oreo/index.html>`__.
-  See `05.03.00 Release
   Notes <http://software-dl.ti.com/processor-sdk-android/esd/docs/05_03_00_07/android/Release_Specific_Supported_Platforms_and_Versions.html>`__
   for full list of modifications.


.. rubric:: Processor SDK Android 05.02.00
   :name: processor-sdk-android-05.02.00

-  This is a maintenance update release of Processor SDK Android for AM57xx
   with Oreo. More details about Oreo can be obtained from
   `here <https://developer.android.com/about/versions/oreo/index.html>`__.
-  See `05.02.00 Release
   Notes <http://software-dl.ti.com/processor-sdk-android/esd/docs/05_02_00_10/android/Release_Specific_Supported_Platforms_and_Versions.html>`__ 
   for full list of modifications.


.. rubric:: Processor SDK Android 05.01.00
   :name: processor-sdk-android-05.01.00

-  This is a maintenance update release of Processor SDK Android for AM57xx
   with Oreo. More details about Oreo can be obtained from
   `here <https://developer.android.com/about/versions/oreo/index.html>`__
-  Multimedia with hardware acceleration is not supported
-  Video decoding up to 720p resolution
-  See `05.01.00 Release
   Notes <http://software-dl.ti.com/processor-sdk-android/esd/docs/05_01_00_11/android/Release_Specific.html#processor-sdk-android-release-notes>`__ for full
   list of modifications.


.. rubric:: Processor SDK Android 05.00.00
   :name: processor-sdk-android-05.00.00

-  Linux Kernel and U-boot are updated to v4.14 and 2018.01 respectively, while
   the pastry continues to be Android-Oreo
-  More details about Oreo can be obtained from
   `here <https://developer.android.com/about/versions/oreo/index.html>`__
-  SD card creation now creates boot partition only with MLO, u-boot.img,
   and uEnv.txt. After flashing the eMMC device by
   `Running Setup Scripts <Overview_Getting_Started_Guide.html#run-setup-scripts>`__,
   SD card is required to boot AM57x IDKs. Keep the SD card plugged in,
   power cycle AM57x IDKs to use MLO and u-boot.img from the SD card
   and the rest from the eMMC. For AM57x GP EVM, SD card can be removed
   before the power cycle to boot Android with everything from the eMMC.
-  VPE is not supported
-  See `05.00.00 Release
   Notes <http://software-dl.ti.com/processor-sdk-android/esd/docs/05_00_00_15/android/Release_Specific.html#processor-sdk-android-release-notes>`__ for full
   list of modifications.

|

.. rubric:: Processor SDK Android 04.03.00
   :name: processor-sdk-android-04.03.00

-  This is a maintenance update release of Processor SDK Android for AM57xx
   with Oreo. More details about Oreo can be obtained from
   `here <https://developer.android.com/about/versions/oreo/index.html>`__
-  See `04.03.00 Release
   Notes <http://software-dl.ti.com/processor-sdk-android/esd/docs/04_03_00_05/android/Release_Specific.html#processor-sdk-android-release-notes>`__ for full
   list of modifications.

|

.. rubric:: Processor SDK Android 04.02.00
   :name: processor-sdk-android-04.02.00

-  This is the first release of the Processor SDK Android for AM57xx
   with Oreo. Both U-Boot and Android Kernel are the same LTS as prior
   Processor SDK releases, i.e. 2016.05 and 4.4 respectively.
-  More details about Oreo can be obtained from
   `here <https://developer.android.com/about/versions/oreo/index.html>`__
-  See `04.02.00 Release
   Notes <http://processors.wiki.ti.com/index.php?title=Processor_SDK_Android_Release_Notes&oldid=232605>`__ for full
   list of modifications.

| 

.. rubric:: Processor SDK Android 04.01.00
   :name: processor-sdk-linux-04.01.00

-  This is the final release of the Processor SDK Android for AM57xx
   with Marshmallow. The next release will be based on Oreo
-  See `04.01.00 Release
   Notes <http://processors.wiki.ti.com/index.php?title=Processor_SDK_Android_Release_Notes&oldid=230917>`__ for full
   list of modifications.

| 

.. rubric:: Processor SDK Android 04.00.00
   :name: processor-sdk-linux-04.00.00

-  This is the first release of the Processor SDK Android which supports
   AM57xx devices.
-  See `04.00.00 Release
   Notes <http://processors.wiki.ti.com/index.php?title=Processor_SDK_Android_Release_Notes&oldid=228953>`__ for full
   list of modifications.

| 

