Using Prebuilt binaries
=======================

.. note::

    Linux machine running Ubuntu is needed for building and flashing Android images to the EVM


The SDK download page provides pre-built Android binaries (``AM62x_XX.YY.ZZ_emmc.tgz``) which can be readily used to flash the AM62 EVM and boot Android.

Extract the contents of the pre-built images tarball and follow the procedure mentioned in `Flashing Instruction`_ page to flash these binaries to the EVM.

::

    tar -zxvf AM62x_XX.YY.ZZ_emmc.tgz

.. _Flashing Instruction: Overview_Flashing.html

