.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_IPC
.. rubric:: Overview
   :name: overview

| 
| IPC is a genric term of Inter-Processor Communication referred widely
  in the industry, but also a package in TI Processor SDK for multi-core
  communication. In generic usage, there are different ways for
  multi-core communication such as OpenCL, DCE, TI-IPC, and etc. In TI's
  IPC package, it uses a set of modules to facilitate the
  inter-processor communication. The documents below provide overview to
  different ways of inter-processor communication and more details by
  following links in each of the subject. The TI IPC User's Guide is
  also provided for reference.

|

.. rubric:: Getting Started
   :name: getting-started

+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------+
| Links                                                                                                                  | Description                                                   |
+========================================================================================================================+===============================================================+
| `Multiple Ways of ARM/DSP Communication <Foundational_Components_IPC.html#multiple-ways-of-arm-dsp-communication>`__   | Provides brief overview of each method and pros and cons      |
+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------+
| `IPC Quick Start Guide <Foundational_Components_IPC.html#ipc-quick-start-guide>`__                                     | Building and setting up examples for IPC with Processor SDK   |
+------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------+

| 

.. rubric:: Technical Documents
   :name: technical-documents

+----------------------------------------------------------------------------------+-----------------------+
| Links                                                                            | Description           |
+==================================================================================+=======================+
| `IPC User's Guide <http://processors.wiki.ti.com/index.php/IPC_Users_Guide>`__   | TI IPC User's Guide   |
+----------------------------------------------------------------------------------+-----------------------+

| 

.. rubric:: Starting IPC project
   :name: starting-ipc-project

+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| Links                                                                                                                      | Description                                                                        |
+============================================================================================================================+====================================================================================+
| `Linux IPC on AM57xx <Foundational_Components_IPC.html#ipc-for-am57xx>`__                                                  | General info on IPC under Linux environment for AM57xx                             |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| `Running IPC example on DRA7xx/AM572x <http://processors.wiki.ti.com/index.php/Running_IPC_Examples_on_DRA7xx/AM572x>`__   | Info on running RTOS IPC examples on DRA7xx/AM572x                                 |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| `Training video on how to Run IPC example on AM572x <https://training.ti.com/am572x-build-run-ipc-examples>`__             | Step-by-step Video on running the IPC examples under Linux environment on AM572x   |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| `AM57x Customizing Multicore Application <http://www.ti.com/lit/an/sprac60/sprac60.pdf>`__                                 | Info and guide to customize memory usage for custom design based on AM57x          |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+
| `Modifying Memory Usage For IPUMM using DRA7xx <http://www.ti.com/lit/an/sprac08a/sprac08a.pdf>`__                         | Info on modifying memory usage of IPU for DRA7xx                                   |
+----------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+

