.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_Migration_Guide

************************************
CoreSDK Linux Migration Guide
************************************

.. rubric:: Overview

This page covers migration information for applications built on top
of the Processor SDK for Linux.

Processor CoreSDK 08.xx Releases
================================

Processor CoreSDK Sitara 08.04
------------------------------
- This is the sixth release on 2021 LTS 5.10 kernel, 2021.01 U-Boot
- ATF 2.7
- OPTEE 3.18
- Yocto Dunfell/3.1
- Platforms Supported : AM62x, AM64x ( Including HS-FS )

Processor CoreSDK Jacinto 08.04
-------------------------------
- This is the fifth release on 2021 LTS 5.10 kernel, 2021.01 U-Boot
- ATF 2.6
- OPTEE 3.12
- Yocto Dunfell/3.1
- Platforms Supported : J721E, J7200, J721S2


Processor CoreSDK 08.03
-----------------------
- This is the fourth release on 2021 LTS 5.10 kernel, 2021.01 U-Boot
- ATF 2.6
- OPTEE 3.12
- Yocto Dunfell/3.1
- Platforms Supported : AM62x


Processor CoreSDK 08.02
-----------------------
- This is the third release on 2021 LTS 5.10 kernel, 2021.01 U-Boot

- Third release on 5.10 kernel and 2021.01 U-boot
- ATF 2.5
- OPTEE 3.12
- Yocto Dunfell/3.1
- Platforms Supported : AM654x , J721E, J721S2, J7200, AM64xx, AM335x, AM43xx, AM57XX


Processor CoreSDK 08.01
-----------------------
- This is the second release on 2021 LTS 5.10 kernel, 2021.01 U-Boot

- Second release on 5.10 kernel and 2021.01 U-boot
- ATF 2.5
- OPTEE 3.12
- Yocto Dunfell/3.1
- Platforms Supported : AM654x , J721E, J7200, AM64xx, AM335x, AM43xx, AM57XX


Processor CoreSDK 08.00
-----------------------
- This is the first release in the 2021 LTS stream, with new versions of Kernel, U-boot, toolchain and Yocto branch.`

- First release on 5.10 kernel and 2021.01 U-boot
- ATF 2.5
- OPTEE 3.12
- Yocto Dunfell/3.1
- Platforms Supported : AM654x , J721E, J7200, AM64xx
