.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_Migration_Guide

************************************
CoreSDK Linux Migration Guide
************************************

.. rubric:: Overview

This page covers migration information for applications built on top
of the Processor SDK for Linux.

Processor CoreSDK 08.xx Releases
================================


Processor CoreSDK 08.00
-----------------------
- This is the first release in the 2021 LTS stream, with new versions of Kernel, U-boot, toolchain and Yocto branch.`

- First release on 5.10 kernel and 2021.01 U-boot
- ATF 2.5
- OPTEE 3.12
- Yocto Dunfell/3.1
- Platforms Supported : AM654x , J721E, J7200, AM64xx

