.. http://processors.wiki.ti.com/index.php/Processor_SDK_Linux_Migration_Guide

************************************
CoreSDK Linux Migration Guide
************************************

.. rubric:: Overview

This page covers migration information for applications built on top
of the Processor SDK for Linux.

Processor CoreSDK 07.xx Releases
================================

Processor CoreSDK 07.03
-----------------------
- Final release on 2020 LTS 5.4 kernel
- AM64  Kernel Support for MMC SDR104 and DDR50 and eMMC HS200 speed modes
- AM64 TSN Switch Support
- AM64 am64xx-sk Support
- J7200 Kernel and Uboot Support for SDR104 speed mode
- J7200 Kernel eMMC HS200 and HS400 speed modes

Processor CoreSDK 07.02
-----------------------
- Introduces AM64XX Support

Processor CoreSDK 07.01
-----------------------
- Introduces J7200 Support
- Redesigned SPL to support HSM Re-architecture
- 2020 LTS based linux SDK for AM335X, AM43XX, AM57XX


Processor CoreSDK 07.00
-----------------------
- This is the first release in the 2020 LTS stream, with new versions of Kernel, U-boot, toolchain and Yocto branch.`

- AM654x GP PG2.0 Support
- J721E-HS Support
