.. http://processors.wiki.ti.com/index.php/IPC_3.x 

`Introduction to Inter-Processor Communication (IPC) for KeyStone and Sitara™ Devices <https://training.ti.com/intro-to-ipc-for-keystone-and-sitara>`__ - The IPC software package is designed to hide the lower-layer hardware complexity of multi-core devices and help users to quickly develop applications for data transfer between cores or devices. 
IPC also maximizes application software reuse by providing a common API interface across all supported platforms, including AM65x, AM57x, 66AK2Gx, 66AK2Ex, 66AK2Hx, TCI663x, TDA3XX, OMAP-L138, OMAP54XX, DRA7XX, and more.
This training video introduces the IPC features and modules, shows how to build the IPC libraries for your platform, examines the RPMsg framework, and provides a look at the included examples and benchmarks.

|

`Building and Running Inter-Processor Communication (IPC) Examples on the AM572x GP EVM <https://training.ti.com/am572x-build-run-ipc-examples>`__ - For TI embedded processors with heterogeneous multi-core architectures – like the AM57x family of devices, which have integrated ARM, DSP, and M4 cores – the TI Processor Software Development Kit (SDK) provides a software component called Inter-processor Communication (IPC). 
This video demonstrates how to build and run IPC examples on the AM572x General Purpose Evaluation Module (GP EVM) using Processor SDK for Linux.

|

IPC Training v2.21 - IPC 3.x Full Training Material :download:`(PowerPoint) </files/IPC_Training_2_21.pptx>` :download:`(PowerPointShow) </files/IPC_Training_2_21.ppsx>` :download:`(PDF) </files/IPC_Training_2_21.pdf>`

|

IPC Lab 1 - Hello :download:`(PowerPoint) </files/IPC_Lab_1_Hello.pptx>` :download:`(PowerPointShow) </files/IPC_Lab_1_Hello.ppsx>` :download:`(PDF) </files/IPC_Lab_1_Hello.pdf>`

IPC Lab 2 - MessageQ :download:`(PowerPoint) </files/IPC_Lab_2_MessageQ.pptx>` :download:`(PowerPointShow) </files/IPC_Lab_2_MessageQ.ppsx>` :download:`(PDF) </files/IPC_Lab_2_MessageQ.pdf>`

IPC Lab 3 - Scalability :download:`(PowerPoint) </files/IPC_Lab_3_Scalability.pptx>` :download:`(PowerPointShow) </files/IPC_Lab_3_Scalability.ppsx>` :download:`(PDF) </files/IPC_Lab_3_Scalability.pdf>`

