---
# yamllint disable rule:line-length

name: "check_toc_txt"

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [master]
    paths:
      - 'source/**'
      - 'configs/*/*_toc.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/texasinstruments/processor-sdk-doc:latest
      options: --entrypoint /bin/bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Update refs and settings
        run: |
          git config --global --add safe.directory "$PWD"
          git switch -C pr
          git fetch --no-tags --depth=1 origin master
          git switch master

      - name: Run rstcheck
        env:
          EVENT_NUMBER: ${{ github.event.number }}
        run: |
          # Disable color output
          export NO_COLOR=true

          # Run the test
          bin/delta.sh -a master -b pr -- ./bin/check_toc_txt.py

          # Prepare summary
          WARNING_COUNT=$(wc -l < _new-warn.log)
          if [ "$WARNING_COUNT" -gt "0" ]; then
            echo "New issues found with check_toc_txt.py:"
            echo '```text'
            cat _new-warn.log
            echo '```'
          else
            echo "No new issues found with check_toc_txt.py"
          fi >> "$GITHUB_STEP_SUMMARY"

          # Prepare the artifacts
          mkdir -p ./results
          echo "$EVENT_NUMBER" > ./results/id
          cp "$GITHUB_STEP_SUMMARY" ./results/summary
          echo "$(wc -l < _new-warn.log)" > ./results/problem-count

          # Exit with error if there are new warnings
          [ "$WARNING_COUNT" -eq "0" ]

      - name: Save results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        if: always()
        with:
          name: results
          path: results/
          retention-days: 1
