---
# yamllint disable rule:line-length

name: "commit-check"

on: [pull_request]  # yamllint disable-line rule:truthy

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  commit-check:
    name: Commit Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Check commit
        uses: commit-check/commit-check-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: true
          branch: false
          author-name: true
          author-email: true
          job-summary: true
          pr-comments: false
