---
# yamllint disable rule:line-length

name: "commit-check"

on: [pull_request]  # yamllint disable-line rule:truthy

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  commit-check:
    name: Commit Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Check commit
        uses: commit-check/commit-check-action@bbb6580f01838e475563514f115ec7ef41c9ddc7  # v2.11.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: true
          branch: false
          author-name: true
          author-email: true
          job-summary: true
          pr-comments: false
