---
# yamllint disable rule:line-length

name: "vale"

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - '**.rst'
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  vale:
    name: vale
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/texasinstruments/processor-sdk-doc:latest
      options: --entrypoint /bin/bash

    steps:
      - name: Prepare GitHub workdir
        run: |
          mkdir -p /github/home/

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          json: true
          escape_json: false
          files: |
            **.rst
            **.md

      - name: Run vale checks on modified files
        uses: vale-cli/vale-action@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          fail_on_error: false  # to be changed when upstream addresses 84
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          version: none
